phrase:
  access_token: 01e34e51ae9b6bcd9c3f8275cfce9e7f79807344d20e0ba8105e2b5226db5db4
  project_id: bc4e35f80b98aeb4092f4c63d4314837
  
  
  push:
    sources:
    - file: ./Booking.json
     params:
        locale_id: en-gb
    

        
        
  pull:
    targets:
    - file: ./Booking_<locale>.json
      params:
        locale_id: es-es
        format: json
        include_translated_keys: true
        include_empty_translations: true
        include_key_descriptions: true
       

       
