phrase:
  access_token: 01e34e51ae9b6bcd9c3f8275cfce9e7f79807344d20e0ba8105e2b5226db5db4
  project_id: bc4e35f80b98aeb4092f4c63d4314837
  file_format: simple_json

  push:
    sources:
      - file: ./Booking.json
        params:
          locale_id: 47d26d0086a3b01f81614ede6cc92609
          update_translations: true
        format_options:
            enable_pluralization: false

  pull:
    targets:
      - file: ./Booking_<locale_id>.json
        params:
          locale_id: 4b21ef64a2c0c5c421fb9aa15908442d
          include_empty_translations: true
          exclude_empty_zero_forms: true
